name: 🌀 Update Profile README

on:
  schedule:
    - cron: "0 9 * * *"  # Every day at 9 AM UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "DATE=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s/{{DATE}}/${{ env.DATE }}/" README.md

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "🤖 Auto-update README [skip ci]" || echo "No changes"
          git push
