name: 🌀 Update Profile README

on:
  schedule:
    - cron: "0 9 * * *"   # Daily at 09:00 UTC
  workflow_dispatch:
  push:
    paths:
      - "README.md"
      - "scripts/**"
      - ".github/workflows/update-readme.yml"

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
          README_PATH: "README.md"
        run: |
          chmod +x scripts/update_profile.py
          python scripts/update_profile.py

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet && echo "No changes" || git commit -m "🤖 Auto-update README"
          git push
